# Docker compose file for running the TensorFlow workflow on a single Docker host
 
version: '3.1'

services:

  # OODT File Manager w/ Solr back-end
  filemgr:
    image: acce/oodt-filemgr-tensorflow:${ACCE_VERSION}
    container_name: filemgr
    build:
      context: ./filemgr
      args:
        - ACCE_VERSION
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      # shared host data volumes
      - $OODT_JOBS:/usr/local/oodt/jobs
      - $OODT_ARCHIVE:/usr/local/oodt/archive
    depends_on:
      - solr
    
  # note: Docker service name must match hostname:8983 in filemgr.properties:
  # org.apache.oodt.cas.filemgr.catalog.solr.url=http://solr:8983/solr/oodt-fm
  solr:
    image: acce/oodt-solr:${ACCE_VERSION}
    container_name: solr
    expose:
      - "8983"
    ports:
      - "8983:8983"

  # OODT Workflow Manager
  wmgr:
    image: acce/oodt-wmgr-tensorflow:${ACCE_VERSION}
    container_name: wmgr
    build:
      context: ./wmgr
      args:
        - ACCE_VERSION
    expose:
      - "9001"
    ports:
      - "9001:9001"
    volumes:
      # shared host data volumes
      - $OODT_JOBS:/usr/local/oodt/jobs
      - $OODT_ARCHIVE:/usr/local/oodt/archive
      - $TENSORFLOW_DATA:/tmp/MNIST_data
    environment:
      - "FILEMGR_URL=http://filemgr:9000/"
      - "WORKFLOW_URL=http://localhost:9001/"
    depends_on:
      - rabbitmq

  # RabbitMQ server
  rabbitmq:
    image: acce/oodt-rabbitmq:${ACCE_VERSION}
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_USER_URL=amqp://oodt-user:changeit@localhost/%2f"
      - "RABBITMQ_ADMIN_URL=http://oodt-admin:changeit@localhost:15672"

  # RabbitMQ clients
  rabbitmq-clients: 
    image: acce/oodt-rabbitmq-clients-tensorflow:${ACCE_VERSION}
    container_name: rabbitmq-clients
    build:
      context: ./rabbitmq-clients
      args:
        - ACCE_VERSION
    environment:
      - "RABBITMQ_USER_URL=amqp://oodt-user:changeit@rabbitmq/%2f"
      - "RABBITMQ_ADMIN_URL=http://oodt-admin:changeit@rabbitmq:15672"
      - "WORKFLOW_URL=http://wmgr:9001/"
    depends_on:
      - rabbitmq
      - wmgr

      