# Specific configuration for running the OODT-Tensorflow application on Minikube

ingress:
  enabled: true

wmgr:
  image: acce/oodt-wmgr-tensorflow
  tag: "3.0"
  replicas: 2
  
solr:
  resources:
    limits:
      memory: "1Gi"
      cpu: "100m"
    requests:
      memory: "1Gi"
      cpu: "100m"