# Specific configuration for running the OODT-Tensorflow application on Minikube

ingress:
  enabled: true
  
solr:
  resources:
    limits:
      memory: "1Gi"
      cpu: "100m"
    requests:
      memory: "1Gi"
      cpu: "100m"

storage:
  accessModes: ReadWriteMany
  size:
    jobs: "1Gi"
    archive: "1Gi"