# Kubernetes deployment file for OODT File Manager and Workflow Manager server
apiVersion: v1
kind: Service
metadata:
  name: filemgr
  labels:
    stack: acce
    component: filemgr-wmgr
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: xmlrpc
  - port: 8983
    targetPort: 8983
    protocol: TCP
    name: solr
  selector:
    stack: acce
    component: filemgr
---
apiVersion: v1
kind: Service
metadata:
  name: wmgr
  labels:
    stack: acce
    component: filemgr-wmgr
spec:
  type: ClusterIP
  ports: 
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: xmlrpc
  selector:
    stack: acce
    component: filemgr-wmgr
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-filemgr-wmgr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: acce
        component: filemgr-wmgr
    spec:
      containers:
      - name: wmgr
        image: acce/oodt-wmgr-tensorflow:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: FILEMGR_URL
          value: "http://filemgr:9000/"
        - name: WORKFLOW_URL
          value: "http://localhost:9001/" 
        volumeMounts:
        - name: oodt-archive 
          mountPath: /usr/local/oodt/archive/
        - name: oodt-jobs
          mountPath: /usr/local/oodt/jobs/
      - name: filemgr
        image: acce/oodt-filemgr-tensorflow:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        - containerPort: 8983
        volumeMounts:
        - name: oodt-archive 
          mountPath: /usr/local/oodt/archive/
        - name: oodt-jobs
          mountPath: /usr/local/oodt/jobs/
      volumes:
      - name: oodt-archive
        emptyDir: {}
      - name: oodt-jobs
        emptyDir: {}