# Kubernetes deployment file for OODT File Manager and Workflow Manager server
apiVersion: v1
kind: Service
metadata:
  name: filemgr
  labels:
    stack: acce
    component: filemgr
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: xmlrpc
  selector:
    stack: acce
    component: filemgr-wmgr
---
apiVersion: v1
kind: Service
metadata:
  name: wmgr
  labels:
    stack: acce
    component: wmgr
spec:
  type: ClusterIP
  ports: 
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: xmlrpc
  selector:
    stack: acce
    component: filemgr-wmgr
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-filemgr-wmgr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: acce
        component: filemgr-wmgr
    spec:
      initContainers:
      - name: data-download
        image: radial/busyboxplus:curl
        command:
          - sh
          - -c
          - |
            mkdir -p /tmp/MNIST_data
            cd /tmp/MNIST_data
            curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
            curl -O http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
            curl -O http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
            curl -O http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
        volumeMounts:
        - name: mnist-data
          mountPath: /tmp/MNIST_data
      containers:
      - name: wmgr
        image: acce/oodt-wmgr-tensorflow:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: FILEMGR_URL
          value: "http://localhost:9000/"
        - name: WORKFLOW_URL
          value: "http://localhost:9001/" 
        volumeMounts:
        - name: oodt-archive 
          mountPath: /usr/local/oodt/archive/
        - name: oodt-jobs
          mountPath: /usr/local/oodt/jobs/
        - name: mnist-data
          mountPath: /tmp/MNIST_data
      - name: filemgr
        image: acce/oodt-filemgr-tensorflow:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: oodt-archive 
          mountPath: /usr/local/oodt/archive/
        - name: oodt-jobs
          mountPath: /usr/local/oodt/jobs/
      - name: rabbitmq-consumer
        image: acce/oodt-rabbitmq-clients-tensorflow:3.0
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_USER_URL
          value: "amqp://oodt-user:changeit@rabbitmq/%2f"
        - name: WORKFLOW_URL
          value: http://localhost:9001
      volumes:
      - name: oodt-archive
        emptyDir: {}
      - name: oodt-jobs
        emptyDir: {}
      - name: mnist-data
        emptyDir: {}