# Kubernetes deployment file for OODT RabbitMQ server
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    stack: acce
    component: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: client-port
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: web-port
  selector:
    stack: acce
    component: rabbitmq-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-rabbitmq-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: acce
        component: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq-server
        image: acce/oodt-rabbitmq:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672
      - name: rabbitmq-producer
        image: acce/oodt-rabbitmq-clients-tensorflow:3.0
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_USER_URL
          value: "amqp://oodt-user:changeit@rabbitmq/%2f"
        - name: RABBITMQ_ADMIN_URL
          value: "http://oodt-admin:changeit@rabbitmq:15672"
        # execute command to keep the container running
        command: ["tail", "-f", "/dev/null"]