# Kubernetes deployment file for OODT RabbitMQ server
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    stack: acce
    component: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: client-port
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: web-port
  selector:
    stack: acce
    component: rabbitmq-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-rabbitmq-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: acce
        component: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq-server
        image: acce/oodt-rabbitmq:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672