# Persistent volumes shared across pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oodt-archive
  labels:
    srack: acce
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oodt-jobs
  labels:
    srack: acce
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi