# Persistent volumes shared across pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oodt-archive
  labels:
    stack: acce
spec:
  accessModes:
    - "{{ .Values.storage.accessModes }}"
  resources:
    requests:
      storage: "{{ .Values.storage.size.archive }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oodt-jobs
  labels:
    stack: acce
spec:
  accessModes:
    - "{{ .Values.storage.accessModes }}"
  resources:
    requests:
      storage: "{{ .Values.storage.size.jobs }}"