# Kubernetes deployment file for OODT Workflow Manager server
apiVersion: v1
kind: Service
metadata:
  name: wmgr
  labels:
    stack: acce
    component: wmgr
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: xmlrpc
  selector:
    stack: acce
    component: wmgr
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-wmgr
spec:
  replicas: {{ .Values.wmgr.replicas }}
  template:
    metadata:
      labels:
        stack: acce
        component: wmgr
    spec:
      initContainers:
       - name: data-downlod
         image: busybox
         command: ["/bin/sh", "-c"]
         args:
         - cd $TENSORFLOW_DATA;
           echo 'Starting data download';
           wget http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz;
           wget http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz;
           wget http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz;
           wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz;
           echo 'Done downloading data';
         env: 
         - name: TENSORFLOW_DATA
           value: /tmp/MNIST_data
         volumeMounts:
         - name: tensorflow-data
           mountPath: /tmp/MNIST_data
      containers:
      - name: wmgr
        # image: acce/oodt-wmgr-tensorflow:3.0
        image: "{{ .Values.wmgr.image }}:{{ .Values.wmgr.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: FILEMGR_URL
          value: "http://filemgr:9000/"
        - name: WORKFLOW_URL
          value: "http://localhost:9001/" 
        volumeMounts:
        - name: oodt-archive 
          mountPath: /usr/local/oodt/archive/
        - name: oodt-jobs
          mountPath: /usr/local/oodt/jobs/
        - name: tensorflow-data
          mountPath: /tmp/MNIST_data
          claimName: oodt-jobs
      volumes: 
      - name: oodt-archive
        persistentVolumeClaim:
          claimName: oodt-archive
      - name: oodt-jobs
        persistentVolumeClaim:
      - name: tensorflow-data
        emptyDir: {}